
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    secretKey: pyk
  datasource:
    url: jdbc:mariadb://localhost:3306/homework?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace   # sql query 에 들어오는 파라메타 값 추적